model:
  base_learning_rate: 1.0e-05
  target: zero123plus.model.MVDiffusion
  params:
    drop_cond_prob: 0.1

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.2 #sudo-ai/zero123plus-v1.2
      custom_pipeline: ./zero123plus

data:
  target: src.data.VDM.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 12
    train:
      target: src.data.VDM.VDMData
      params:
        validation: false
        image_dir : "./dataset/rendering_result/render_ortho_normal"
        hue_flag: True
        crop_flag: True 
        flip_flag: False

    validation:
      target: src.data.VDM.VDMData
      params:
        validation: true
        image_dir : "./dataset/rendering_result/render_ortho_normal"
        hue_flag: True
        crop_flag: True 
        flip_flag: False


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 5000
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: 5000
    gradient_clip_val: 1.0
    val_check_interval: 80000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
